### ISSUE TITLE
silly question, how to install

### ISSUE THREAD

**Issue by jmugan** [Tugcga/PyRecastDetour#5]
Hi, thanks for the awesome work. How do I install it?

I tried git clone and then import like in the README but I either got a circular import error or no-module-found error. 

Do I have to install RecastNavigation first? And do I need the C++ binding files?

Sorry, I'm not very familiar with working with C++ bindings and such.

Thanks!

**Comment by Tugcga** [comment]
Nothing special required. You need only Python x64. Then create file with your program (```my_program.py``` for example), clone the repository and place the folder ```recastdetour``` near ```my_program.py```. From the ```recastdetour``` you need actually only ```__init__.py``` file and ```*.pyd``` file for your version of the Python. So, if you use Python 3.9, then your setup should be the following:
```
my_program.py
recastdetour\
    __init__.py
    Py39RecastDetour.pyd
```

Then you write in ```my_program.py```
```
import recastdetour as rd
```

and all should works.

Check that you use Python x64 instead of x32, because ```*.pyd``` files in the repository does not compatible with x32 version.

**Comment by jmugan** [comment]
I'm running x64, but that doesn't seem to work for me. It gives me an Import error both on my mac and on my linux machine. Maybe it only works on Windows?

```
(base) jmugan@JMugan:~/temp/PyRecastDetour$ ls
README.md      my_program.py  recastdetour/
(base) jmugan@JMugan:~/temp/PyRecastDetour$ python my_program.py 
Traceback (most recent call last):
  File "my_program.py", line 1, in <module>
    import recastdetour as rd
  File "/Users/jmugan/temp/PyRecastDetour/recastdetour/__init__.py", line 9, in <module>
    from . import Py37RecastDetour as rd
ImportError: cannot import name 'Py37RecastDetour' from 'recastdetour' (/Users/jmugan/temp/PyRecastDetour/recastdetour/__init__.py)
```

**Comment by Tugcga** [comment]
I am sorry, but yes, it works only on Windows. Because *.pyd file is actually *.dll file.

**Comment by jmugan** [comment]
Ah, cool, thanks. I guess I could try to build it myself for linux and mac using PyBind11 and these files? https://github.com/Tugcga/PyRecastDetour-Sources

**Comment by Tugcga** [comment]
Yes, you can try.

**Comment by jmugan** [comment]
Thanks! So I should read https://pybind11.readthedocs.io/en/latest/basics.html and then apply it to https://github.com/Tugcga/PyRecastDetour-Sources? Is there anything else I should look at for documentation on how to do it? Is that all the files? I guess I'm looking for files with `#include <pybind11/pybind11.h>` in them?

Thanks for any help you can give and thanks for making such a great set of repositories.

**Comment by Tugcga** [comment]
At first you should setup your environment and build the simplest c++ module for Python. For example, one function ```int add(int x, int y)```. And then, when the pipline is clear, apply it in the more complex situation for building PyRecastDetour. But in fact this module exports only one class with several public methods.

For using ```PyBind11``` you need:
* Includes for Python
* Includes for PyBind
* Libs for Python (*.lib files)

For building PyRecastDetour you additionally need:
* Recastnavigation includes
* Recastnavigation libs

I load these additional files to the [release page](https://github.com/Tugcga/PyRecastDetour-Sources/releases). But this files was used for building windows version. May be they are incompatible with Linux and MacOS. So, may be you will need manually build Recastnavigation library and use corresponding files.

**Comment by jmugan** [comment]
Thank you so much! I'll give it a try and report back how it goes!

**Comment by jmugan** [comment]
Thank you so much, do you have the files with pybind wrappers? For example, something with 
`#include <pybind11/pybind11.h>` and
```
PYBIND11_MODULE(example, m) {
    m.doc() = "pybind11 example plugin"; // optional module docstring

    m.def("add", &add, "A function that adds two numbers");
}
```
We saw the original .h and .cpp files and the dlls but we didn't see any files with the pybind in them. If you don't have them, no problem, just wanted to check. Thanks again!

**Comment by Tugcga** [comment]
I am sorry, but I don't understand your question. Let we repeat some basic steps for building Python module from c++:
1. Install PyBind11 module for your version of the Python
2. Create c-file with the following code
```
#include <pybind11/pybind11.h>

int add(int i, int j) {
	return i + j;
}

PYBIND11_MODULE(ExampleModule, m) {
	m.def("add", &add, "A function which adds two numbers");
}
```
3. Include ```pybind11.h``` file from installed PyBind11 module folder and link ```*.lib``` files from Python ```libs``` folder (```F:\Python310\libs``` for example)
4. Compile your c-file
5. It should works

**Comment by unwave** [comment]
@jmugan 
> any files with the pybind in them

https://github.com/Tugcga/PyRecastDetour-Sources/blob/main/PyRecastDetour.cpp

### For Visual Studio:

A guide by MS: [Write C++ extensions for Python - Visual Studio (Windows) | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019#use-pybind11)
A shorter version: [Speeding up Python with C++ and Pybind11](https://jtt94.github.io/posts/2020/08/pythoncpp/)

**Comment by unwave** [comment]
The pybind11 libs locations for C/C++ > General Additional Include Directories:
```cmd
Microsoft Windows [Version 10.0.19044.2006]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>python -m pybind11 --includes
-IC:\Users\user\AppData\Local\Programs\Python\Python39\Include -IC:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pybind11\include
```

And `python39.lib` for the linker. Linker > General Additional Library Directories
```cmd
Microsoft Windows [Version 10.0.19044.2006]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>python
Python 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, sys
>>> p = os.path.join(os.path.dirname(sys.executable), 'libs')
>>> print(p); os.startfile(p)
C:\Users\user\AppData\Local\Programs\Python\Python39\libs
```

Take other the project settings from: https://jtt94.github.io/posts/2020/08/pythoncpp/

**Comment by Tugcga** [comment]
I think that the problem consists in the compiling of the module for Linux instead of Windows. So, it's impossible to use Visual Studio as described in your links.
